//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Registro
    {
        public int NumRegistro { get; set; }
        public Nullable<int> NumSemana { get; set; }
        public string TipoConsulta { get; set; }
        public string TemaConsulta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> Carnet { get; set; }
        public string Observaciones { get; set; }
    }
}
