//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultasAEDEntities : DbContext
    {
        public ConsultasAEDEntities()
            : base("name=ConsultasAEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignatura> Asignaturas { get; set; }
        public virtual DbSet<C_Registro> C_Registro { get; set; }
        public virtual DbSet<Docente> Docentes { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
    }
}
